// Autogenerated by gameplay-luagen
#ifndef LUA_AUDIOCONTROLLER_H_
#define LUA_AUDIOCONTROLLER_H_

namespace egret
{

// Lua bindings for AudioController.
int lua_AudioController__gc(lua_State* state);

void luaRegister_AudioController();

}

#endif
